### ISSUE TITLE
minetest.get_node_or_nil - not always checked for nil return value

### ISSUE THREAD

**Issue by JDCodeIt** [petermaloney/walking_light#6]
The meaning of "nil" return value is that the block is not loaded where that node is. A review of all the code where nil can be returned is needed, so that appropriate action is taken:
- Sometimes just ignore the action
- Sometimes you may wish to use a voxel_manip to read the map position.

See an example at the dev wiki https://dev.minetest.net/minetest.get_node_or_nil

**Comment by petermaloney** [comment]
in most places, it seems like the code wouldn't cause any issues...but can_add_light() was wrong, and remove_light() most likely would have put air in those places.

see commit ad465894a80c9b373a1f8bb5fe48324b258a0d55 (a merge) or ad465894a80c9b373a1f8bb5fe48324b258a0d55 for the changes.

So I'll close this...reopen it if you think it's wrong, or send a pull request.
